### ISSUE TITLE
Suggested fix for elements that are in ScrollViews afaik.

### ISSUE THREAD

**Issue by hegelstad** [AndreiCalazans/rn-tooltip#1]
Great little lib!

**Comment by hegelstad** [comment]
https://github.com/necolas/react-native-web/issues/702

**Comment by hegelstad** [comment]
https://gist.github.com/hegelstad/5a8d0681512c618c68a17805ea002e4d

**Comment by AndreiCalazans** [comment]
closed https://github.com/AndreiCalazans/rn-tooltip/pull/3
