### ISSUE TITLE
How to Trigger To Hide?

### ISSUE THREAD

**Issue by TeorikDeli** [AndreiCalazans/rn-tooltip#10]
Hi,

How can I trigger the tooltip to hide? I added some button in a tooltip, and one of the buttons navigates to another screen, but tooltip stays open when I press it. I'd like to hide it when I press the button in that tooltip. I already set the toggleOnPress={true} and already tried to call this.toggleTooltip(); in the onPress event of the button.

Thanks.

**Comment by AndreiCalazans** [comment]
Hey, you will need to save a reference to the tooltip and call the `toggleTooltip`. Like `this.tooltipRef.toggleTooltip()`

See https://github.com/AndreiCalazans/rn-tooltip/blob/master/src/Tooltip.js#L53

**Comment by alveshelio** [comment]
Hi @AndreiCalazans,

Like TeorikDeli, I have a button (Paste) that when I click, I'd like to close the tooltip. 

I'm quite new to React-Native and I'm not sure I fully understand what you mean by 

> you will need to save a reference to the tooltip and call the toggleTooltip. Like this.tooltipRef.toggleTooltip()

Do you think you could provide an example?

This is what I have:
I have a file called Tooltip.tsx
```
import React from 'react'
import { StyleSheet, View } from 'react-native'
import { default as RNTooltip} from 'rn-tooltip'
import Paste from './Paste'
import PopoverContent from './PopoverContent'

interface TooltipProps {
  onPasteHandler: () => void
  children: React.ReactChild
}

const Tooltip: React.FC<TooltipProps> = ({ children, onPasteHandler }) => {
  const renderPopover = () => (
    <PopoverContent>
      <Paste onPaste={onPasteHandler} />
    </PopoverContent>
  )

  

  return (
    <View style={styles.container}>
      <RNTooltip
        withOverlay={false}
        withPointer={false}
        width={100}
        height={50}
        toggleOnPress={true}
        containerStyle={styles.tooltipContainer}
        highlightColor='transparent'
        popover={renderPopover()}
      >
        {children}
      </RNTooltip>
    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  tooltipContainer: {
    flex: 1,
    marginTop: 15,
    marginLeft: -50,
    backgroundColor: 'rgb(51, 51, 51)',
  }
})

export default React.memo(Tooltip)
```
In my Paste component, I have an action to paste the content from the clipboard, however I'd like to know how I could also hide the Tooltip when I presse Paste.

Thank you

**Comment by AndreiCalazans** [comment]
Reference to how to do this: https://github.com/AndreiCalazans/rn-tooltip/issues/39#issuecomment-553502283
