### ISSUE TITLE
UnableToResolveError: Unable to resolve module `react-native/Libraries/Renderer/shims/NativeMethodsMixin` from `/Users/longshilin/Workspace/project/Lsw/Lsw/node_modules/rn-tooltip/src/Tooltip.js`: Module does not exist in the module map or in these directories:

### ISSUE THREAD

**Issue by TestsLing** [AndreiCalazans/rn-tooltip#18]
UnableToResolveError: Unable to resolve module `react-native/Libraries/Renderer/shims/NativeMethodsMixin` from `/Users/longshilin/Workspace/project/Lsw/Lsw/node_modules/rn-tooltip/src/Tooltip.js`: Module does not exist in the module map or in these directories:

<img width="371" alt="WX20190701-143034@2x" src="https://user-images.githubusercontent.com/40593646/60415108-cf1f8200-9c0c-11e9-8034-000879f52f19.png">

**Comment by TestsLing** [comment]
env 
"react-native": "0.44.3",
"rn-tooltip": "^1.1.2",

**Comment by AndreiCalazans** [comment]
Thanks to @isnotgood this will no longer happen
https://github.com/AndreiCalazans/rn-tooltip/pull/17
