### ISSUE TITLE
Ho to make content scrollable

### ISSUE THREAD

**Issue by VitaliiTsurkan** [AndreiCalazans/rn-tooltip#25]
Content that located in my tooltip element is very big, I don't want to show it all - just some part and then scroll to others part? I've tried to put ScrollView inside but it doesn't work.  How to do that?

**Comment by AndreiCalazans** [comment]
Here is how:

I have an Example App use for testing and I added an example of this there. 

https://github.com/AndreiCalazans/rnTooltipTester/blob/master/App.tsx#L163-L189

**Comment by VitaliiTsurkan** [comment]
It work's. Thanks a lot;
