### ISSUE TITLE
*ask* automatically call tooltip without pressing it first

### ISSUE THREAD

**Issue by rinoarmadiaz** [AndreiCalazans/rn-tooltip#48]
hi, i wanted to know if i can show the tooltip without actually need to press the tooltip first?

thanks!

**Comment by AndreiCalazans** [comment]
Yes, you can save a reference of the tooltip and call the `toggleTooltip` method.
https://github.com/AndreiCalazans/rn-tooltip/blob/master/src/Tooltip.js#L55

Like, `<Tooltip ref={this.myLocalTooltipRef} />`

Then, `this.myLocalTooltipRef.toggleTooltip()`.

**Comment by rinoarmadiaz** [comment]
cool, many thanks!!

**Comment by rinoarmadiaz** [comment]
Hi, can i ask one more question? sorry for out of the topic issues.

how can i move my triangle to the left of the tooltip like my image below? 

![image](https://user-images.githubusercontent.com/31609667/69228696-9893d500-0bb6-11ea-9f56-1371ede11703.png)

**Comment by AndreiCalazans** [comment]
The tooltip triangle position is automatically calculated by the position of the wrapped element, I can guess by looking at the screenshot you are wrapping that entire view at the bottom with the tooltip. If you want the tooltip to point to a specific element you must wrap that element by the tooltip.

**Comment by jgushai** [comment]
Hi, I am using using tooltip reference  to automatically open the tooltip when screen is loaded.I need to prevent tooltip from closing when users click some where else on the screen. is there a way I can achive it ?
