### ISSUE TITLE
[Android] back button press is consumed without doing anything when popover is showing

### ISSUE THREAD

**Issue by jayshah123** [AndreiCalazans/rn-tooltip#49]
On pressing device back button on Android when the Modal is open, Nothing happens.
Ideally it should hide the modal/popover, or make `isVisible` a controlled prop.

**Comment by jayshah123** [comment]
or expose onRequestClose as a separate prop

**Comment by AndreiCalazans** [comment]
This is what the `onClose` handler is for, you can achieve the same thing. You have to imperatively handle this logic inside `onClose`.
