### ISSUE TITLE
Open tooltip in compomentDidMount

### ISSUE THREAD

**Issue by S530669** [AndreiCalazans/rn-tooltip#53]
I am trying to open tooltip in componentDidMount without clicking and close it automatically after 5 seconds.
Could you please help?

**Comment by ptcasa** [comment]
You should use :

`
componentDidMount () {
//open Tooltip first
this.Tooltip.toggleTooltip();
//set timeout 5000 ms to close tooltip
   setTimeout(() => {this.Tooltip.toggleTooltip()}, 5000);
}

 _
and use Tooltip component with ref like this

<Tooltip 
     popover={'Ok'}
	ref = {ref => {this.Tooltip = ref;}}
>
<Text>{'ClickMe'}</Text>
</Tooltip>
`

**Comment by Talha-Jawed** [comment]
@S530669 any solution?

**Comment by MDG-MMeksasi** [comment]
@S530669 hello, Please how did you manage to do this?
