### ISSUE TITLE
How to Make Tooltip to adapt width as per text size

### ISSUE THREAD

**Issue by MaganAnkur** [AndreiCalazans/rn-tooltip#66]
Explain what you did
Use Tooltip on a text component

Expected behaviour
Tooltip should be dynamic depending on text size

Describe the bug
Tooltip size dont change depending on text, and long text are getting cut-off

**Comment by ricbermo** [comment]
Use this `height="auto"`

**Comment by Rhombk** [comment]
That doesn't seem to work all too well when the Triangle isDown prop is set to true, leaving a gap between the pointer and the tooltip blob
