### ISSUE TITLE
Tooltip is not getting centred to parent element

### ISSUE THREAD

**Issue by MaganAnkur** [AndreiCalazans/rn-tooltip#67]
Parent Element : 
`<Tooltip isVisible = {true}>
                <Text style = {{borderWidth : 1, borderColor : 'black', alignSelf : 'flex-start'}}>Perss Here</Text>
  </Tooltip>`

Tooltip : 

`export const Tooltip = ({
    title = '',
    description = ' ',
    isVisible = false,
    children,
}) => {
    const tooltipRef = useRef(null);

    useEffect(() => {
        isVisible && tooltipRef.current.toggleTooltip();
    }, [isVisible]);

    const renderPopover = () => {
        const textStyle = 'text-sm text-white';
        return (
            <>
                <Text style={[tailwind(`${textStyle}`), { fontFamily: 'Poppins-SemiBold' }]}>{title}</Text>
                <Text style={[tailwind(`${textStyle}`), { fontFamily: 'Poppins-Regular' }]}>{description}</Text>
            </>
        );
    };

    return (
        <RNToolTip
            height="auto"
            popover={renderPopover()}
            withOverlay={false}
            ref={tooltipRef}
            actionType="press"
            containerStyle={tailwind('bg-teal rounded-sm ')}>
            {children}
        </RNToolTip>
    );
};
![Simulator Screen Shot - iPhone 8 - 2021-02-17 at 00 41 58](https://user-images.githubusercontent.com/42070594/108161656-76d71580-70b9-11eb-882b-06b99857281c.png)
`

**Comment by OrionPro** [comment]
I have finalized the positioning of the tooltip and much more, you can fork yourself and make the necessary changes - https://github.com/OrionPro/rn-tooltip . There is a separate option to enable center positioning. If you do not choose positioning, it automatically puts to the right side or left. You can see my code.
