### ISSUE TITLE
How do I custom your isVisble variable?

### ISSUE THREAD

**Issue by QuocHuynhHD** [AndreiCalazans/rn-tooltip#69]
![image](https://user-images.githubusercontent.com/43953469/112250361-d2358e00-8c8b-11eb-93a8-819a21fded7c.png)

**Comment by ArekChr** [comment]
`
  export const ThemedTooltip2: FC<ThemedTooltip2Props> = ({ description, isVisible, children, onClose }) => {
      const prevVisible = useRef(false);
  
      useEffect(() => {
          if (isVisible && prevVisible.current == false) {
              ref.current?.toggleTooltip();
          }
          prevVisible.current = isVisible;
      }, [isVisible]);
  
      const ref = useRef<RNTooltip>(null);
  
      return (
          <RNTooltip
              onClose={onClose}
              ref={ref}
              popover={<ThemedText>{description}</ThemedText>}>
              {children}
          </RNTooltip>
      );
  };
`
