### ISSUE TITLE
Android issue padding between pointer and container

### ISSUE THREAD

**Issue by Talha-Jawed** [AndreiCalazans/rn-tooltip#74]
Simply not working on Android, maybe you need to upgrade the android system.

![image](https://user-images.githubusercontent.com/39768820/122589156-5a53e580-d079-11eb-89c9-e0192ff70b07.png)

- React Native Version: 0.63.4
- rn-tooltip: 3.0.1

- [x] iOS look perfect.

```
 <Tooltip
            width={170}
            ref={myLocalTooltipRef}
            withOverlay={false}
            popover={
                <EmojisLike
                    handleClick={(e) => selectEmoji(e)}
                />
            }
     />
```

Any luck how to fix this extra padding issue?

**Comment by Talha-Jawed** [comment]
@AndreiCalazans

**Comment by irfanismaya20** [comment]
Yes I'm too Android issue padding between pointer and container but in ios perfect

**Comment by ChristinaKrapivina** [comment]
The same issue on Android 11, works fine on Android 10.
Any suggestions, how to fix it, would be helpful.

**Comment by gayathri-nair03** [comment]
Any update on this issue? @AndreiCalazans

**Comment by Shruthyshanthraj** [comment]
any update on this issue ?

**Comment by AndreiCalazans** [comment]
https://github.com/AndreiCalazans/rn-tooltip/pull/84/files

**Comment by jenipharachelcw** [comment]
This issue still exists when tooltip position is top and height is "auto" for dynamic content
