### ISSUE TITLE
Wrong position measurement

### ISSUE THREAD

**Issue by ArekChr** [AndreiCalazans/rn-tooltip#76]
"react-native": "0.64.2"

<img width="622" alt="image" src="https://user-images.githubusercontent.com/24796318/126465425-3cbf7984-2686-481a-abc3-8b184fb33138.png">

`
        <View style={{ flex: 1, backgroundColor: GRAY_DARK_5, justifyContent: 'center' }}>
            <Tooltip actionType="press" popover={<Text>Info here</Text>}>
                <Text>Press me</Text>
            </Tooltip>
        </View>
`

**Comment by nitin41** [comment]
I'm also facing this same issue in android.

**Comment by ammarahm-ed** [comment]
@ArekChr Before you put a thumbs down know that this is open source. You faced a problem, fix it or ask nicely for support. The maintainer is not on your payroll.
