### ISSUE TITLE
Wrong position in android  [Help Wanted]

### ISSUE THREAD

**Issue by kamalpandey** [AndreiCalazans/rn-tooltip#8]
This issue is still persisting. Might be scrollview is causing some issue

```
<ScrollView>
 <View>  
  <Tooltip
    popover={<Text style={{ color: Colors.white }}>{tooltipLabel}</Text>}
    containerStyle={{
      height: "auto",
      alignSelf: "center"
     }}
    width="90%"
    withPointer={false}
  >
    <FontAwesome name="question-circle" size={20} />
  </Tooltip>
 </View>
</ScrollView>
```

![img_20181002_164536](https://user-images.githubusercontent.com/4987931/46345330-e0c6ff80-c663-11e8-9e0d-b0024a178eac.jpg)

**Comment by AndreiCalazans** [comment]
Strange, try to debug the layout around the tooltip. What can usually happen is a style being applied to Content wrapper which you are not passing to the containerStyle. Note that we wrap the popover with a View so we can position it. 

I tried replicating your design and I was successful. See example:

**code**
```JavaScript

<View style={{ flexDirection: 'row', alignItems: 'center' }}> 
    <Text>Report Title</Text>
    <Tooltip
      popover={<Text style={{ color: 'white' }}>Test</Text>}
      containerStyle={{
        height: "auto",
        alignSelf: "center"
      }}
      width="90%"
      withPointer={false}
    >
      <Text style={{ margin: 10, fontSize: 20, backgroundColor: 'yellow' }}>?</Text>
    </Tooltip>
  </View>
  <TextInput style={{ height: 38, borderRadius: 10, backgroundColor: 'lightgray' }} />
```

**Android**
<img width="309" alt="screen shot 2018-10-02 at 09 27 24" src="https://user-images.githubusercontent.com/20777666/46348443-67102100-c625-11e8-987b-a99627341c2b.png">

**IOS**
<img width="309" alt="screen shot 2018-10-02 at 09 27 24" src="https://user-images.githubusercontent.com/20777666/46348319-084aa780-c625-11e8-8bd5-39a241466a37.gif">


You might need to investigate into the layout to see what's going, what's making the tooltip position incorrectly, it's most likely a style which you are missing.

**Comment by AndreiCalazans** [comment]
Worst case scenario you can copy and paste the code from Tooltip and tweak the positioning to your needs or change how we are Wrapping the view to adapt to your situation. However, I believe you can get it working with the current implementation. 

https://github.com/AndreiCalazans/rn-tooltip/blob/master/src/Tooltip.js
