### ISSUE TITLE
How do I determine where the hint appears

### ISSUE THREAD

**Issue by M2021SA** [AndreiCalazans/rn-tooltip#91]
Hi, 
I have a problem using the tooltip
The first is how to determine where the tooltip appears, for example, I want it to appear above

 Second, how do I cancel the pointer when determining the appearance or how to  give it style none,
Here is my code
```
<Tooltip
          height={55}
          width="50%"
          withPointer={true}
          backgroundColor={isDark ? theme.text : '#00000029'}
          withOverlay={false}
          popover={
            <Text  style={styles.item_msg}>
              This is a test.
            </Text>
          }
        >
          <Exclamation size={18} color={theme.text} style={styles.icon} />
        </Tooltip>
```

**Comment by AndreiCalazans** [comment]
> The first is how to determine where the tooltip appears

The tooltip doesn't allow you to set where it will position. It does that for you based on some internal calculations that looks for the most optimal space. 


> Second, how do I cancel the pointer when determining the appearance or how to give it style none, 

You can use a local state  with the `withPointer` and that should toggle it.
